// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUyU5hA134DR49uUzvbBmd1PsVEU78Ldc',
    appId: '1:667219675773:web:09c933b727a77807babf14',
    messagingSenderId: '667219675773',
    projectId: 'login-app-b82df',
    authDomain: 'login-app-b82df.firebaseapp.com',
    storageBucket: 'login-app-b82df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-IXxxISrm7mN31VBG6JRjOgnnbDoNolE',
    appId: '1:667219675773:android:a1f2777f944a9442babf14',
    messagingSenderId: '667219675773',
    projectId: 'login-app-b82df',
    storageBucket: 'login-app-b82df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM-Cuwr3z8wyAuAhEQD_cDTs-PRqVS5yk',
    appId: '1:667219675773:ios:404c4570cacb1567babf14',
    messagingSenderId: '667219675773',
    projectId: 'login-app-b82df',
    storageBucket: 'login-app-b82df.firebasestorage.app',
    androidClientId: '667219675773-tdr24aphl5kjkhvqhrvtd3mlloc49uag.apps.googleusercontent.com',
    iosClientId: '667219675773-ldamdok01slqijelj3unafcl3ervfcvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUyU5hA134DR49uUzvbBmd1PsVEU78Ldc',
    appId: '1:667219675773:web:2af5e0a3e8d2050ababf14',
    messagingSenderId: '667219675773',
    projectId: 'login-app-b82df',
    authDomain: 'login-app-b82df.firebaseapp.com',
    storageBucket: 'login-app-b82df.firebasestorage.app',
  );
}
